config/routes.rb
Rails.application.routes.draw do
  root  "flights#index"

  get "signup" => "users#new"

  get "login" => "sessions#new"

  post "login" => "sessions#create"

  get "logout" => "sessions#destroy"

  get "home" => "static_pages#home"

  post "/auth/:provider/callback" => "sessions#create"

  resources :users
  resources :flights
  resources :bookings
end

app/models/airline.rb
class Airline < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  has_many :planes

  def self.available
    Airline.where(:id => Plane.owner_id).pluck(:name, :price)
  end

  def self.the_name
    get_attr
    @name
  end

  def self.price
    @price
  end

  private
    def self.get_attr
      @name = []
      @price = []
      available.each do |item|
        @name << item[0]
        @price << item[1]
      end
    end
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :landings, :foreign_key => :destination_id, :class_name => "Flight"
  has_many :take_offs, :foreign_key => :departure_id, :class_name => "Flight"
  validates :name, presence: true
  validates :location, presence: true

  def self.locations
    Airport.distinct.pluck(:location, :id)
  end

  def  self.position(id)
    Airport.where(id: id.to_i).pluck(:name)
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  before_save :create_ticket_no

  belongs_to :user
  belongs_to :flight
  validates :no_of_passengers, presence: true
  validates :flight_id, presence: true

  has_many :passengers
  accepts_nested_attributes_for :passengers

  private
    def create_ticket_no
      self.ticket_no = self.id + 5000
    end
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :destination, :class_name => "Airport"
  belongs_to :departure, :class_name => "Airport"

  has_many :bookings
  has_many :planes

  accepts_nested_attributes_for  :bookings, allow_destroy: true

  def self.get_date
    Flight.pluck("DISTINCT departure_date").sort
  end

  def self.formatted_departure_date
    date = get_date
    date.map{|date|date.strftime("%B %-d, %Y")}
  end

  def date
    self.departure_date.strftime("%B %-d, %Y")
  end
  def time
    self.departure_date.strftime("%I:%M %p")
  end

  def self.search(params)
    if params[:flight]
      date = params[:flight][:departure_date].to_date
      date = date.beginning_of_day..date.end_of_day
      dest_id = params[:flight][:destination_id].to_i
      dept_id = params[:flight][:departure_id].to_i
      self.where(destination_id: 7, departure_id:  2, departure_date: date)
    else
    end
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: 50, minimum: 1}
  validates :email, presence: true, length: {maximum: 100, minimum: 4}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
  has_many :booking_records, :foreign_key => :passenger_id, :class_name => "Booking"
end

app/models/plane.rb
class Plane < ActiveRecord::Base
  belongs_to :airline
  belongs_to :flight
  validates :name, presence: true

  def self.available(id)
    Plane.where(flight_id:  id).pluck(:name, :owner_id)
  end

  def self.plane_name(flight_id)
    @flight_id = flight_id
    make_available
    @name
  end

  def self.owner_id
    @owner_id
  end

  private
    def self.make_available
      @name = []
      @owner_id = []
      available(@flight_id).each do |item|
        @name << item[0]
        @owner_id << item[1].to_i
      end
    end
end

app/models/user.rb
class User < OmniAuth::Identity::Models::ActiveRecord
  before_save {self.email = email.downcase}
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: 50, minimum: 1}
  validates :email, presence: true, length: {maximum: 100, minimum: 4}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}

  has_many :booking_records, :foreign_key => :user_id, :class_name => "Booking"

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flight_form = Flight.new
    @airports = Airport.locations
    @dates = Flight.formatted_departure_date
    @flight = Flight.search(params)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    auth = request.env["omniauth.auth"]
    if !auth.nil?
      user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
      @auth_user = user
   elsif auth.nil?
      user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in(user)
      flash[:notice] = "Log In Successful"
      redirect_to root_url
    else
      flash[:alert] = "Error in page"
      render "new"
    end
  end
  def failure

  end

  def destroy
    log_out if logged_in?
    flash[:notice] = "Signed Out!"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      @current_user = @user
      flash[:success] = "Welcome to Eagles Flight"
      redirect_to root_url
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
      log_in user
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/new.html.erb
<%provide(title: "Booking")%>
<div>
<h4 class="center-align">Booking Form</h4>

</div>

app/views/flights/_flights.html.erb
<%flight = @flight%>
<% num = params[:flight][:booking][:no_of_passengers].to_i %>
<div class="row">
  <div class="col s6 col l6 offset-l2">
  <%#binding.pry%>
    From:  <%=Airport.position(params[:flight][:departure_id]).shift%>
  </div>
  <div class="col s6 col l3">
    To:  <%=Airport.position(params[:flight][:destination_id]).shift%>
  </div>
</div>

<table class="bordered highlight responsive-table">
  <thead>
    <tr>
        <th data-field="id">Id</th>
        <th data-field="name">Airlines</th>
        <th data-field="name">Planes</th>
        <th data-field="date">Date of Departure</th>
        <th data-field="time">Time of Departure</th>
        <th data-field="cost">Price for <%=num%></th>
    </tr>
  </thead>
    <tbody>
     <% flight.each do |f|%>
        <%Plane.plane_name(f.id).each do |plane|%>
          <% airline_name = Airline.the_name%>
          <%price = Airline.price%>
          <% cost = (number_to_currency(((price.shift + f.price)* num), :unit => "$")) %>
          <tr>
            <td><%= radio_button_tag :flight_id, f.id, true, class: "our-radio"%></td>
            <td><%= airline_name.shift%></td>
            <td><%= plane%></td>
            <td><%=f.date%></td>
            <td><%=f.time%></td>
            <td><%=cost%></td>
          </tr>
        <%end%>
      <%end%>
    </tbody>
  </table>
<div class="center-align padded">
   <button type="submit" name=nil class="btn waves-light waves-effect">SEARCH</button>
</div>

app/views/flights/index.html.erb
<%provide(:title, "Flights")%>
<h4 class="center-align">Search for a flight to that special city</h4>
<div class="form-wrapper">
  <div class="row">
     <%=form_for @flight_form, url:  root_path, method: "get" do |f|%>
      <div class="col s12">
          <div class="row">
            <div class="col s6">
              <%=f.label :departure_id, "Your take off point?"%>
              <div class="collection">
              <%=f.select :departure_id, options_for_select(@airports), required: true, class: "collection-item input-field"%>
              </div>
            </div>
            <div class="col s6">
              <%=f.label :destination_id, "Your destination?"%>
              <div class="collection">
              <%=f.select :destination_id, options_for_select(@airports), required: true, class: "collection-item input-field"%>
            </div>
            </div>
          </div>
      </div>
      <br/>
      <div class="col s12">
          <div class="row">
            <div class="col s6">
              <%=f.label :departure_date, "Your flight date?"%>
              <div class="collection">
              <%=f.select :departure_date, options_for_select(@dates), required: true, class: "collection-item input-field"%>
              </div>
            </div>
            <div class="col s6">
              <%=f.fields_for :booking do |booking_form|%>
              <%=booking_form.label :no_of_passengers, "How many people?"%>
              <div class="collection">
              <%=booking_form.select :no_of_passengers, options_for_select([[1,1], [2,2], [3,3], [4,4] ,[5,5]]), required: true, class: "input-field collection-item"%>
            </div>
            <%end%>
            </div>
          </div>
      </div>
      <br/>
      <div class="center-align">
         <button type="submit" name="send" class="btn waves-light waves-effect">SEARCH</button>
      </div>
       <%end%>
    </div>
</div>

<div class="rendered-page">
<% if params[:flight] && !@flight.nil? && params[:flight][:departure_id] != params[:flight][:destination_id]%>
  <h4 class="center-align">Make a choice of Flight.</h4>
  <div class="search-table">
  <%= form_tag new_booking_path, method: "get" do %>
    <%= hidden_field_tag :no_of_passengers,  params[:no_of_passengers] %>
    <%= render "flights/flights"%>
   <% end %>
   <%elsif params[:send]%>
   <h4 class="center-align">No Flights in this category</h4>
<%end%>
</div>
</div>

app/views/flights/new.html.erb
<%provide(:title, "Flights")%>
<div class="form-wrapper">
  <div class="row">
     <%=form_for :flight, method: "get" do |f|%>
     <%=f.fields_for :airport do |airport_form|%>
      <div class="col s12">
          <div class="row">
            <div class="col s6">
              <%=airport_form.label :departure_id, "From"%>
              <%=airport_form.collection_select(:departure_id, Airport.locations, :name, :id )%>
            </div>
            <div class="col s6">
              <%=airport_form.label :destination_id, "To"%>
              <%=airport_form.collection_select(:destination_id, Airport.locations, :name, :id )%>
              <%end%>
            </div>
          </div>
      </div>
      <div class="col s12">
          <div class="row">
            <div class="col s6">
              <%=f.label :departure_date, "Flight Date"%>
              <%=f.select_date :departure_date, options_from_collection_for_select(Flight.get_departure_date, :departure_date, date_separator: '/')%>
            </div>
            <div class="col s6">
              <%=f.fields_for :booking do |booking_form|%>
              <%=booking_form.label :no_of_passengers, "Number of Tickets"%>
              <%=booking_form.number_select :no_of_passengers, value: 1, max: 5, min: 1%><%= f.number_field :age, class: "form-control", value: 18, min:6  %>
            <%end%>
            </div>
          </div>
      </div>
      <div class="col s4 offset-s4">
         <button type="submit" class="btn waves-light waves-effect">Submit</button>
      </div>
       <%end%>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Eagles Flight Inc</h5>
        <p class="grey-text text-lighten-4">Connecting you to the world beyond.</p>
        <br/>
        <h6 class="white-text">Mike Munroe</h6>
         <p class="grey-text text-lighten-4">Eagles Flight has given me access to the safest and cheapest flight life style.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h6 class="white-text">Follow us</h6>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">facebook</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright center-aligned" >
    © 2014 Copyright Text
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar-fixed" id="head-view">
    <nav>
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Eagles Flight</a>
        <ul class="right hide-on-med-and-down">
          <li class="active"><a href="/">Home</a></li>
          <%if !logged_in?%>
         <li><a href="<%= signup_path%>">Sign Up</a></li>
         <li><a href="<%= login_path%>">Log In</a></li>
         <li><%= link_to "Sign in with Twitter", "/auth/twitter" %></li>
         <li><%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
         <% else %>
         <li><a href="#">Booking History</a></li>
          <li><a href="<%= logout_path%>">Log Out</a></li>
          <%end%>
        </ul>
        <a href="#" data-activates="mobile-demo" class="button-collapse right"><i class="fa fa-bars"></i></a>
        <ul class="side-nav" id="mobile-demo">
          <li class="active"><a href="/">Home</a></li>
          <%if !logged_in?%>
         <li><a href="<%= signup_path%>">Sign Up</a></li>
         <li><a href="<%= login_path%>">Log In</a></li>
         <% else %>
         <li><a href="#">Booking History</a></li>
          <li><a href="<%= logout_path%>">Log Out</a></li>
          <%end%>
        </ul>
      </div>
    </nav>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%=yield(:title)%> | Eagles Flight</title>
  <%= stylesheet_link_tag    "application", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%=render "layouts/shim"%>
</head>
<body>
  <%=render "layouts/header"%>
  <div class="container mini-body">
  <% if flash[:notice].present? %>
  <div>
    <script type="text/javascript">
        Materialize.toast("<%= flash[:notice]%>", 3000, "rounded");
    </script>
  </div>
  <% end %>
  <div class="container">
  <%=render "layouts/error_messages"%>
    <%= yield %>
    </div>
    </div>
</body>
</html>

app/views/static_pages/home.html.erb
<%provide(:title, "Home")%>
<div class="homepage-body">
  <div>
    <h1 class="large-text">Welcome to Eagles Flight</h1>
  </div>
</div>

app/views/users/new.html.erb
<%provide(:title, 'Sign Up')%>
<h4 class="center-align">Sign Up</h4>
<div class="row form-wrapper">
  <%= form_for @user do |f|%>
      <div class="row">
        <div class="input-field col l6 s12 offset-l3">
          <%= f.label :name, "Full Name"%>
          <%= f.text_field :name,class: "validate", required: true%>
        </div>
      </div>
      <div class="row">
        <div class="input-field col l6 s12 offset-l3">
          <%= f.label :email, "Email"%>
          <%= f.email_field :email, class: "validate", required: true%>
        </div>
      </div>
        <div class="row">
          <div class="input-field col l6 s12 offset-l3">
            <%= f.label :password, "Password"%>
            <%= f.password_field :password, class: "validate", required: true%>
          </div>
        </div>
      <div class="row">
        <div class="input-field col l6 s12 offset-l3">
          <%= f.label :password_confirmation, "Confirm Password"%>
          <%= f.password_field :password_confirmation, class: "validate", required: true%>
        </div>
      </div>
      <div class="row">
        <div class="col s4 offset-s3 offset-l3 l4">
           <button type="submit" class="btn waves-light waves-effect">Sign Up</button>
        </div>
        <div class="col s4 l4">
            <%= link_to "Log In", login_path, class: "btn waves-effect waves-light"%>
        </div>
      </div>
  <%end%>
</div>